- name: Download Alertmanager binary
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
    checksum: "sha256:{{ alert_manager_checksum }}"

- name: Extract Alertmanager binary
  unarchive:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "{{ alertmanager_install_dir }}"
    remote_src: yes
    creates: "{{ alertmanager_install_dir }}/alertmanager-{{ alertmanager_version }}"

- name: Rename Alertmanager binary
  file:
    src: "{{ alertmanager_install_dir }}/alertmanager-{{ alertmanager_version }}/alertmanager"
    dest: "{{ alertmanager_install_dir }}/alertmanager"
    state: link
    force: yes

- name: Create Alertmanager configuration directory
  file:
    path: "/etc/alertmanager/"
    state: directory

- name: Copy Alertmanager configuration file
  copy:
    src: "{{ alertmanager_config_src }}"
    dest: "{{ alertmanager_config_dest }}"

- name: Create Alertmanager service file
  template:
    src: ./templates/alertmanager.service.j2
    dest: "{{ alertmanager_service_dest }}"
  notify:
    - Reload systemd 
    - Start alertmanager_service

                                           
